name: Build Android APK

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # Matches tags like v1.0.0, v2.1.3, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: |
          cd App/frontend
          npm install

      - name: Install Expo CLI
        run: npm install -g expo eas-cli

      - name: Build Android APK
        working-directory: App/frontend
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform android --profile production --non-interactive --output-dir builds

      - name: Rename and Move APK to Root
        run: |
          mv App/frontend/builds/*.apk ./SpotHole.apk

      - name: Upload APK as a Release Asset
        uses: actions/upload-artifact@v3
        with:
          name: SpotHole-APK
          path: ./SpotHole.apk
